package by.training.barbershop.controller;

public enum CommandType {
    LOGIN,LOGOUT,REGISTRATION,GO_TO_REGISTRATION,GO_TO_LOGIN,
    GO_TO_ABOUT_US,HOME,ERROR, LANGUAGE,SERVICES,BARBERS,ORDER,
    ORDER_WAITING,GO_TO_ORDER_WAITING,CLIENT_PROFILE, CLIENT_PERSONAL_DATA,
    GO_TO_CLIENT_EDIT_PROFILE,CLIENT_EDIT_PERSONAL_DATA,CLIENT_ORDERS,
    CLIENT_REMOVE_ORDER,CLIENTS_LIST,VIEW_ORDERS,CHANGE_USER_STATUS,
    CHANGE_ORDER_STATUS,REMOVE_ORDER,

}
