package by.training.task04.controller;

public enum CommandName {
    BLOCK_ACCOUNT, FIND_ACCOUNT, NEGATIVE_BALANCE_BANK,
    POSITIVE_BALANCE_BANK, SORT_CLIENT_ACCOUNT,
    TOTAL_BALANCE_CLIENT, POSITIVE_NEGATIVE_SUM_CLIENT;
}
