package by.training.task03.controller;

public enum CommandName {
    BUBBLE_SORT_INCREASING, INSERTION_SORT_INCREASING, MERGE_SORT_INCREASING,
    SELECTION_SORT_INCREASING,
    SHAKER_SORT_INCREASING, SHELL_SORT_INCREASING,
    BUBBLE_SORT_DECREASING, INSERTION_SORT_DECREASING, MERGE_SORT_DECREASING,
    SELECTION_SORT_DECREASING,
    SHAKER_SORT_DECREASING, SHELL_SORT_DECREASING,
    MATRIX_MULTIPLY, MATRIX_ADDITION, MATRIX_SUBTRACTION;
}
